-- ==========================================================
-- Deel Analytics Bootstrap (ACCOUNTADMIN, no ownership xfers)
-- ==========================================================

-- ---------- Edit these ----------
SET SCHEMA_SUFFIX = '';                 -- '' for prod, '_CI' for CI, etc.
SET DB            = 'DEEL_ANALYTICS';
SET WH            = 'TRANSFORMING';
SET TARGET_USER   = 'TARGET_USER';            -- <=== set to your Snowflake username

-- Optional resource monitor
SET RESOURCE_MONITOR_NAME = 'DEEL_AE_MONITOR';
SET CREDIT_QUOTA          = 50;             -- credits

-- ---------- Derived identifiers ----------
SET RAW_SCHEMA     = CONCAT($DB, '.RAW',     $SCHEMA_SUFFIX);
SET CURATED_SCHEMA = CONCAT($DB, '.CURATED', $SCHEMA_SUFFIX);
SET MARTS_SCHEMA   = CONCAT($DB, '.MARTS',   $SCHEMA_SUFFIX);

SET RAW_FF    = CONCAT($RAW_SCHEMA, '.CSV_FF');
SET RAW_STAGE = CONCAT($RAW_SCHEMA, '.RAW_STAGE');

-- ==========================================================
-- 1) Roles & grants to YOUR user
-- ==========================================================
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RAW_LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;
CREATE ROLE IF NOT EXISTS ANALYST;
CREATE ROLE IF NOT EXISTS ALERTER;
CREATE ROLE IF NOT EXISTS DEEL_PLATFORM_ADMIN;

-- Simple hierarchy
GRANT ROLE RAW_LOADER  TO ROLE DEEL_PLATFORM_ADMIN;
GRANT ROLE TRANSFORMER TO ROLE DEEL_PLATFORM_ADMIN;
GRANT ROLE ANALYST     TO ROLE DEEL_PLATFORM_ADMIN;
GRANT ROLE ALERTER     TO ROLE DEEL_PLATFORM_ADMIN;

-- Grant working roles to YOUR user (TARGET_USER)
GRANT ROLE TRANSFORMER         TO USER IDENTIFIER($TARGET_USER);
GRANT ROLE RAW_LOADER          TO USER IDENTIFIER($TARGET_USER);
GRANT ROLE ANALYST             TO USER IDENTIFIER($TARGET_USER);
GRANT ROLE ALERTER             TO USER IDENTIFIER($TARGET_USER);
GRANT ROLE DEEL_PLATFORM_ADMIN TO USER IDENTIFIER($TARGET_USER);

-- Make TRANSFORMER default
ALTER USER IDENTIFIER($TARGET_USER) SET DEFAULT_ROLE = TRANSFORMER;

-- ==========================================================
-- 2) Warehouse, Database, Schemas
-- ==========================================================
-- (ACCOUNTADMIN can create these directly)
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($WH)
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS IDENTIFIER($DB);

-- Create (or ensure) suffixed schemas
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($RAW_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($CURATED_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($MARTS_SCHEMA);

-- ==========================================================
-- 3) Privileges (warehouse/db/schemas)
-- ==========================================================
-- Warehouse usage
GRANT USAGE ON WAREHOUSE IDENTIFIER($WH) TO ROLE RAW_LOADER;
GRANT USAGE ON WAREHOUSE IDENTIFIER($WH) TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE IDENTIFIER($WH) TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE IDENTIFIER($WH) TO ROLE ALERTER;

-- Database usage
GRANT USAGE ON DATABASE IDENTIFIER($DB) TO ROLE RAW_LOADER;
GRANT USAGE ON DATABASE IDENTIFIER($DB) TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE IDENTIFIER($DB) TO ROLE ANALYST;
GRANT USAGE ON DATABASE IDENTIFIER($DB) TO ROLE ALERTER;

-- RAW: loader + transformer can create
GRANT USAGE            ON SCHEMA IDENTIFIER($RAW_SCHEMA) TO ROLE RAW_LOADER;
GRANT USAGE            ON SCHEMA IDENTIFIER($RAW_SCHEMA) TO ROLE TRANSFORMER;
GRANT CREATE TABLE     ON SCHEMA IDENTIFIER($RAW_SCHEMA) TO ROLE RAW_LOADER;
GRANT CREATE STAGE     ON SCHEMA IDENTIFIER($RAW_SCHEMA) TO ROLE RAW_LOADER;
GRANT CREATE FILE FORMAT ON SCHEMA IDENTIFIER($RAW_SCHEMA) TO ROLE RAW_LOADER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA IDENTIFIER($RAW_SCHEMA) TO ROLE TRANSFORMER;

-- CURATED: transformer writes; analyst reads
GRANT USAGE            ON SCHEMA IDENTIFIER($CURATED_SCHEMA) TO ROLE TRANSFORMER;
GRANT USAGE            ON SCHEMA IDENTIFIER($CURATED_SCHEMA) TO ROLE ANALYST;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA IDENTIFIER($CURATED_SCHEMA) TO ROLE TRANSFORMER;

-- MARTS: transformer writes; analyst + alerter read
GRANT USAGE            ON SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE TRANSFORMER;
GRANT USAGE            ON SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE ANALYST;
GRANT USAGE            ON SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE ALERTER;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE TRANSFORMER;

-- Future grants for readers
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($CURATED_SCHEMA) TO ROLE ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA IDENTIFIER($CURATED_SCHEMA) TO ROLE ANALYST;

GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE ANALYST;

GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE ALERTER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA IDENTIFIER($MARTS_SCHEMA) TO ROLE ALERTER;

-- ==========================================================
-- 4) Resource monitor (optional)
-- ==========================================================
SET _stmt =
  'CREATE RESOURCE MONITOR IF NOT EXISTS "' || $RESOURCE_MONITOR_NAME || '" ' ||
  'WITH CREDIT_QUOTA = ' || $CREDIT_QUOTA || ' ' ||
  'TRIGGERS ON 90 PERCENT DO SUSPEND ON 100 PERCENT DO SUSPEND_IMMEDIATE';
EXECUTE IMMEDIATE $_stmt;

SET _stmt =
  'ALTER WAREHOUSE "' || $WH || '" SET RESOURCE_MONITOR = "' || $RESOURCE_MONITOR_NAME || '"';
EXECUTE IMMEDIATE $_stmt;

-- ==========================================================
-- 5) RAW convenience objects (create as ACCOUNTADMIN — we granted CREATE)
-- ==========================================================
CREATE FILE FORMAT IF NOT EXISTS IDENTIFIER($RAW_FF)
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS IDENTIFIER($RAW_STAGE);

-- Done.
